### ISSUE TITLE
decode error and scrolling bug

### ISSUE THREAD

**Issue by pollux78** [Davidoc26/wallpaper-selector#19]
scrolling rlly fast for a while can bring this error up and when your scrolling enough you can make it break out which spawns a bunch of wallpapers at once

flatpak run io.github.davidoc26.wallpaper_selector

(wallpaper-selector:3): Gtk-WARNING **: 14:16:50.717: Unknown key gtk-modules in /home/pollux/.var/app/io.github.davidoc26.wallpaper_selector/config/gtk-4.0/settings.ini

(wallpaper-selector:3): Adwaita-WARNING **: 14:16:50.758: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
thread 'tokio-runtime-worker' panicked at src/provider/wallhaven.rs:101:14:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at src/provider/wallhaven.rs:101:14:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
thread 'tokio-runtime-worker' panicked at src/provider/wallhaven.rs:101:14:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
thread 'tokio-runtime-worker' panicked at src/provider/wallhaven.rs:101:14:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
thread 'tokio-runtime-worker' panicked at src/provider/wallhaven.rs:101:14:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
thread 'tokio-runtime-worker' panicked at src/provider/wallhaven.rs:101:14:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
thread 'tokio-runtime-worker' panicked at src/provider/wallhaven.rs:101:14:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
thread 'tokio-runtime-worker' panicked at src/provider/wallhaven.rs:101:14:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }

https://github.com/user-attachments/assets/07a77888-7fff-494d-bb70-fa1e1c09d8bd

**Comment by VortexAcherontic** [comment]
Can confirm, first time user (flatpak version) and it does not work with the following error:

```
thread 'tokio-runtime-worker' panicked at src/provider/wallhaven.rs:101:14:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
```

**Comment by Davidoc26** [comment]
> Can confirm, first time user (flatpak version) and it does not work with the following error:
> 
> ```
> thread 'tokio-runtime-worker' panicked at src/provider/wallhaven.rs:101:14:
> called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }
> ```

Although this is not related to the issue, the problem is that cloudflare protection is blocking requests to the api, there is probably nothing that can be done about it.
