### ISSUE TITLE
Crash after selecting Preferences

### ISSUE THREAD

**Issue by sabriunal** [Davidoc26/wallpaper-selector#7]
wallpaper-selector is closing itself if I select the Prefereces option from the Main Menu.

```
RUST_BACKTRACE=1 flatpak run io.github.davidoc26.wallpaper_selector.Devel
thread 'main' panicked at 'Failed to retrieve template child. Please check that it has been bound and has a #[template_child] attribute.', /run/build/wallpaper-selector/_flatpak_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.8/src/subclass/widget.rs:1305:17
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
RUST_BACKTRACE=full flatpak run io.github.davidoc26.wallpaper_selector.Devel
thread 'main' panicked at 'Failed to retrieve template child. Please check that it has been bound and has a #[template_child] attribute.', /run/build/wallpaper-selector/_flatpak_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.8/src/subclass/widget.rs:1305:17
stack backtrace:
   0:     0x55f25a32ceaa - <unknown>
   1:     0x55f25a34d69e - <unknown>
   2:     0x55f25a327805 - <unknown>
   3:     0x55f25a32cc75 - <unknown>
   4:     0x55f25a32e45f - <unknown>
   5:     0x55f25a32e19b - <unknown>
   6:     0x55f25a32eb6c - <unknown>
   7:     0x55f25a32e8c2 - <unknown>
   8:     0x55f25a32d35c - <unknown>
   9:     0x55f25a32e612 - <unknown>
  10:     0x55f2599b7e13 - <unknown>
  11:     0x55f259a14d3d - <unknown>
  12:     0x55f259a49166 - <unknown>
  13:     0x55f259a35f50 - <unknown>
  14:     0x55f259a492ca - <unknown>
  15:     0x55f259a36ad9 - <unknown>
  16:     0x7f68f25e3349 - g_type_create_instance
  17:     0x7f68f25c648c - <unknown>
  18:     0x7f68f25c7db5 - g_object_newv
  19:     0x55f25a2d919a - <unknown>
  20:     0x55f25a2d871a - <unknown>
  21:     0x55f2599cacc7 - <unknown>
  22:     0x55f2599b91cd - <unknown>
  23:     0x55f2599ce523 - <unknown>
  24:     0x55f259a20bdf - <unknown>
  25:     0x55f2599f479e - <unknown>
  26:     0x7f68f25c0569 - g_closure_invoke
  27:     0x7f68f25d3f1f - <unknown>
  28:     0x7f68f25daf3f - g_signal_emit_valist
  29:     0x7f68f25db093 - g_signal_emit
  30:     0x7f68f270cad5 - <unknown>
  31:     0x7f68f2bbb696 - <unknown>
  32:     0x7f68f2bb7338 - <unknown>
  33:     0x7f68f25c0569 - g_closure_invoke
  34:     0x7f68f25d3f1f - <unknown>
  35:     0x7f68f25daf3f - g_signal_emit_valist
  36:     0x7f68f25db093 - g_signal_emit
  37:     0x7f68f28c5803 - <unknown>
  38:     0x7f68f25c0798 - <unknown>
  39:     0x7f68f25dae7b - g_signal_emit_valist
  40:     0x7f68f25db093 - g_signal_emit
  41:     0x7f68f29aee53 - <unknown>
  42:     0x7f68f25c3b6a - g_cclosure_marshal_VOID__BOXEDv
  43:     0x7f68f25c0798 - <unknown>
  44:     0x7f68f25dae7b - g_signal_emit_valist
  45:     0x7f68f25db093 - g_signal_emit
  46:     0x7f68f29ab408 - <unknown>
  47:     0x7f68f29acde7 - <unknown>
  48:     0x7f68f29b061b - <unknown>
  49:     0x7f68f29783ca - <unknown>
  50:     0x7f68f2b362e9 - <unknown>
  51:     0x7f68f2b3e790 - <unknown>
  52:     0x7f68f2a00442 - <unknown>
  53:     0x7f68f2a00bbb - <unknown>
  54:     0x7f68f2a331f0 - <unknown>
  55:     0x7f68f2c4e631 - <unknown>
  56:     0x7f68f2c7bb74 - <unknown>
  57:     0x7f68f25c0569 - g_closure_invoke
  58:     0x7f68f25d3f1f - <unknown>
  59:     0x7f68f25da80b - g_signal_emit_valist
  60:     0x7f68f25db093 - g_signal_emit
  61:     0x7f68f2c7f780 - <unknown>
  62:     0x7f68f2cd26b7 - <unknown>
  63:     0x7f68f24c4cdb - g_main_context_dispatch
  64:     0x7f68f24c51e8 - <unknown>
  65:     0x7f68f24c52b4 - g_main_context_iteration
  66:     0x7f68f27033ed - g_application_run
  67:     0x55f259a2021f - <unknown>
  68:     0x55f259a20349 - <unknown>
  69:     0x55f2599cef17 - <unknown>
  70:     0x55f259a1787c - <unknown>
  71:     0x55f2599d3b2b - <unknown>
  72:     0x55f259a2242e - <unknown>
  73:     0x55f2599eb661 - <unknown>
  74:     0x55f25a322dac - <unknown>
  75:     0x55f2599eb63a - <unknown>
  76:     0x55f259a178ee - <unknown>
  77:     0x7f68f2030b80 - __libc_start_main
  78:     0x55f2599b848e - <unknown>
  79:                0x0 - <unknown>
```

**Comment by Davidoc26** [comment]
Thanks for opening the issue.

It's weird because I couldn't reproduce it.
As I see you used the dev build. It seems to me that the problem is in the incorrect build of the program, since there is no such problem in the published release build (at least I hope).

**Comment by sabriunal** [comment]
I forgot to mention I tested on Development build.

There is no error on the released version, on Flathub (https://flathub.org/apps/details/io.github.davidoc26.wallpaper_selector)

**Comment by Davidoc26** [comment]
Well, as I already wrote, I could not reproduce this error even in dev build, most likely the problem is in the build of the project. I'm building it via "Gnome builder".
How are you building the program?

**Comment by sabriunal** [comment]
I have tested on Ubuntu 22.10 with flatpak-builder 1.2.2, flatpak version of org.gnome.Builder 43.5 from flathub.

I'am going to test the bug, today on Fedora and GNOME OS. I will inform you soon.

Thanks.

**Comment by sabriunal** [comment]
I have tested on Fedora 37 with GNOME Builder and got the same error.

[Ekran Kaydı - 2023-02-05 19-02-50.webm](https://user-images.githubusercontent.com/6218679/216830385-5ccac33a-c13d-437e-8e4d-f4f7421deb6a.webm)
